### ISSUE TITLE
Common function for iterating and ordering service mesh release versions.

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshkit#17]
**Current Behavior**
- Adapters retrieve service mesh releases by version number.
- Service meshes make releases of both new versions and patched versions.
- Meshery needs to be cognizant of this fact and present the Meshery user with the latest service mesh releases in descending chronological order by release version #, not by release date.
- GitHub's release API has some limitations to be aware of. 

**Desired Behavior**
- See the meshery-istio adapter as [an example implementation](https://github.com/layer5io/meshery-istio/pull/157/files#diff-a08b6d46fa69bac973bb200a889870f7800300ec26484719173aa82206c0259dR34-R65) that should be up-leveled to `meshery-adapter-library` as a universal function of all Meshery Adapters.

**Implementation**
- Account for service mesh specific release naming by allowing individual adapters to define release terms like "alpha", "rc", "edge", "stable", and so on. Different service mesh project have different version naming schemes.

**Acceptance Tests**
1. `func getLatestReleaseNames ()` and `func GetLatestReleases()` are centralized as a function in this adapter-library.

**Comment by mgfeller** [comment]
Suggestion for implementation: 

- define an interface Filter (with a default implementation) to remove releases not of interest (e.g. "rc")
- define an interface Comparator (with a default implementation) to compare versions
- lots of tests

Thus, mesh specific release naming can easily be handled.
