### ISSUE TITLE
Add a 'go vet' GitHub action

### ISSUE THREAD

**Issue by jbyers19** [meshery/meshkit#172]
**Desired Behavior**
Add new GitHub action to run `go vet ./...`. This will help catch errors like this one: #170 

---
**Resources**
https://www.alexedwards.net/blog/ci-with-go-and-github-actions

**Comment by leecalcote** [comment]
Nice. As you think on this, will you reflect on what [golanglint-ci ](https://github.com/golangci/golangci-lint) brings to the table in comparison? We've incorporated its use in the past to aid in speeding up the time that the checks take to execute. What do you think?

**Comment by leecalcote** [comment]
Oh, I see your notes [here](https://github.com/meshery/meshkit/pull/171#issue-1205082804) now.

@alphaX86, @Revolyssup, @gr455, @hexxdump, @mgfeller, @piyushsingariya, @Zanda256, .... thoughts?

**Comment by jbyers19** [comment]
@leecalcote, I was digging into the `golangci-lint` tool and configuration. I didn't realize before that it runs `go vet ./...` itself. So this issue is invalid. I'll close it.
