### ISSUE TITLE
update gh workflows to ubuntu version 22.04 and label-commenter issue

### ISSUE THREAD

**Issue by StarTrooper08** [meshery/meshkit#246]
**Description**

Just a few weeks back we updated the GitHub actions workflow specifically to ubuntu 22.04 in meshery/meshery repository cause ubuntu-latest is still on 20.04 and it gives some deprecated warning(Even some workflows were using 18.04v).

So should we update GitHub workflow for meshkit repository ?

And I can see some warnings for the label-commenter node.js version.
(peaceiris/actions-label-commenter@v1.10 is using node 16)
Even for label-commenter actions, we either need to mention specific versions or mention as the latest

Issue reference:
https://github.com/meshery/meshery/pull/6689

**Expected Behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/72031540/209790917-5e460b47-0ea9-4ef8-9fed-05cb017aadd3.png)
**Environment:**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

**Comment by StarTrooper08** [comment]
@acald-creator @leecalcote what should we do here? 
Should we update it or keep it as the latest for meshkit repository?

**Comment by leecalcote** [comment]
I'll yield to @acald-creator's perspective.

**Comment by acald-creator** [comment]
Closing for now, GitHub will migrate the ubuntu version to the latest when the update is done
