### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by Philip-21** [meshery/meshkit#286]
### Creating a Readme in the utils package 

 Since the Utils Package is a central component in meshKit, i would like to create a readme in the Utils package to help other devs understand the code base , i propose giving a brief explanation on each  of the packages or components located in the  utils package.   
[Utils Package](https://github.com/meshery/meshkit/tree/master/utils)

**Comment by leecalcote** [comment]
Thank you, @Philip-21

**Comment by Philip-21** [comment]
can i still go on with the readme for this ?

**Comment by leecalcote** [comment]
@Philip-21 yes, that would be good.
