### ISSUE TITLE
Replace the Logo of Layer5 with Meshery in config.yml workflow

### ISSUE THREAD

**Issue by ShivangShandilya** [meshery/meshkit#296]
**Description**

Currently, we are using the Logo of Layer5 instead of Meshery. This repository is under the organization Meshery, so, there should be an image of Meshery.

**How to resolve this**

- Go to .github and replace this welcome image with the new one:

- Make sure to display the images conditionally, based on the theme selected by user.
Here's the sample code:

```
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/GiorgosXou/Random-stuff/main/Programming/StackOverflow/Answers/70200610_11465149/w.png">
  <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/GiorgosXou/Random-stuff/main/Programming/StackOverflow/Answers/70200610_11465149/b.png">
  <img alt="Meshery Logo" src="">
</picture>
```

New images are:

![image](https://user-images.githubusercontent.com/101946115/231824547-c6364b75-0108-4fcf-afaf-bebc06a57049.png)

![image](https://user-images.githubusercontent.com/101946115/231824562-f680a2c2-a6c2-49bd-bb57-516a358b4563.png)

- Download these images, and upload with an appropriate name. Make sure to use conditional rendering as described above.

- After uploading the image, and removing the previous image, go to .github/config.yml folder and update the reference to previous image to the new image in the following part:

```
firstPRMergeComment: >
  Thanks for your contribution to the Layer5 and Meshery community! :tada:
   
  ![Congrats!](https://raw.githubusercontent.com/meshery/meshery.io/master/.github/welcome/Layer5-celebration.png)
  &nbsp; &#9; &nbsp; &#9;  &nbsp; &#9;  &nbsp; &#9; :star: Please leave a [star on the project](../stargazers). :smile:
```
Here, replace `![Congrats!](https://raw.githubusercontent.com/meshery/meshery.io/master/.github/welcome/Layer5-celebration.png)` with the code

```
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/GiorgosXou/Random-stuff/main/Programming/StackOverflow/Answers/70200610_11465149/w.png">
  <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/GiorgosXou/Random-stuff/main/Programming/StackOverflow/Answers/70200610_11465149/b.png">
  <img alt="Shows a black logo in light color mode and a white one in dark color mode." src="https://user-images.githubusercontent.com/25423296/163456779-a8556205-d0a5-45e2-ac17-42d089e3c3f8.png">
</picture>
```

make sure to change the image sources with the path to image in the folder where you upload it.

- That's it.

**Comment by Gaurav-create948** [comment]
Hello community i would like to contribute in this issue my current tech stack is html, css, reactjs, nodejs, mongodb.

**Comment by om2137** [comment]
@ShivangShandilya  if this issue is still open can i work on this ?

**Comment by shivangshandilya** [comment]
@om2137 Thank you for the contribution😁 but I would say this is unprofessional behavior on your part. One should always wait for maintainers to assign the issue before working on it. Maintainer would have first assigned @Gaurav-create948 as he was the one who approached first and if by any circumstance he couldn't do it then only it would have been assigned to you. 

It's fine now but do keep this in mind for your future contributions not only in Meshery but with any other Open source project also

**Comment by om2137** [comment]
@ShivangShandilya Hey, I apologize for directly opening the PR without being assigned. 
I thought we had to directly open PR, as some organizations do not assign the issue in order to open a PR. 
once again I apologize, and I will keep this in mind in my further contributions.

**Comment by ShivangShandilya** [comment]
> @ShivangShandilya Hey, I apologize for directly opening the PR without being assigned. I thought we had to directly open PR, as some organizations do not assign the issue in order to open a PR. once again I apologize, and I will keep this in mind in my further contributions.

It's fine @om2137 I wasn't scolding you or anything 😂😂. We all started from somewhere right and we all made mistakes. Just keep in mind to always read CONTRIBUTING guidelines of the project you're contributing to 😄
