### ISSUE TITLE
[Docs] Error links in readme

### ISSUE THREAD

**Issue by Ghat0tkach** [meshery/meshkit#317]
**Description**

The layer5 communtiy welcome guide link is leading to wrong link
![image](https://github.com/meshery/meshery-osm/assets/59855919/8083557c-8e17-4f44-9f53-4d5f67132f42)

**Expected Behavior**

it could be possible that the link is deleted or we can switch it with the [newcomer's guide](https://layer5.io/community/newcomers)
**Screenshots**

**Environment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

**Comment by Ghat0tkach** [comment]
in either of the cases  , i would love to work on this issue

**Comment by leecalcote** [comment]
@Ghat0tkach, thanks. Yes, please do copy what has been done in one of the other readmes.

**Comment by Ghat0tkach** [comment]
@leecalcote , i raised the same issue on the meshery-osm repo . Please have a look
https://github.com/meshery/meshery-osm/issues/245
