### ISSUE TITLE
[chore] update Go to 1.21, and update relevant pkgs

### ISSUE THREAD

**Issue by saurabh100ni** [meshery/meshkit#365]
### Desired Behaviour
Need to update `Go` to `1.21` in `go.mod` and in `Dockerfile`, and also `Makefile`

- Minor chore on updating `meshkit` and `meshery-adapter-library`

**Comment by leecalcote** [comment]
@nebula-aac @theBeginner86 we might need to process this post-haste

**Comment by AryanSharma9917** [comment]
Hey @yash37158, are you working on this issue?

**Comment by yash37158** [comment]
you can go for it @AryanSharma9917

**Comment by Ayush9026** [comment]
@yash37158 will i do it .

**Comment by yash37158** [comment]
Yes @Ayush9026, you can start working on this

**Comment by nebula-aac** [comment]
I forgot to mention that this is already done, however there seems to be an indirect package that creeped in that may affect how other adapters build using the latest from `meshkit` even without a release. I'm researching now.

**Comment by yash37158** [comment]
If this issue is already resolved, we can close it. @nebula-aac
