### ISSUE TITLE
[Helm Repo Schema] Please include standard field validation for a URL.

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshkit#371]
Please include standard field validation for a URL.

_Originally posted by @leecalcote in https://github.com/meshery/meshkit/pull/367#discussion_r1327647679_

**Comment by leecalcote** [comment]
@Yashsharma1911 i think this might be done now. Is that right?

**Comment by Yashsharma1911** [comment]
> @Yashsharma1911 i think this might be done now. Is that right?

Yes, closing this issue
