### ISSUE TITLE
[CI] Workflow to validate the compatibility of MeshKit with Meshery Server

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshkit#413]
**Current Behavior**

Currently, there isn't a workflow which checks the compatibility of MeshKit changes on PRs with latest Meshery Server backend code. And, maintainers and contributors have to manually check the compatibility.

> Here compatibility refers to go.mod changes and different pkgs imported by different MeshKit clients like Meshery Server, mesheryctl etc.

**Desired Behavior**

1. Create a workflow that can check the compatibility of changes in MeshKit.
2. Workflow should run on each PR

For reference check recording at https://discuss.layer5.io/t/meshery-build-release-meeting-nov-9th-2023/4170

---
**Resources**

**Alternatives / Additional Context**

**Comment by leecalcote** [comment]
Why a separate workflow?
