### ISSUE TITLE
Rename `design.meshmodel.io` to `id.design.meshery.io`.

### ISSUE THREAD

**Issue by MUzairS15** [meshery/meshkit#472]
@MUzairS15 this is to be `design.meshery.io`, right?

_Originally posted by @leecalcote in https://github.com/meshery/meshkit/pull/468#discussion_r1515553022_
            

The renaming of the annotation will impact UI clients.
The changes must be coordinated with the affected UI clients.

**Comment by AllenOps08** [comment]
I want to work on this. Is anyone currently working on this @leecalcote? Also can you explain a bit about this.

**Comment by leecalcote** [comment]
Thank you @AllenOps08. 👏

**Comment by leecalcote** [comment]
@AllenOps08 here is a bit of background about the purpose of this annotation - [Greenfield: Tracking newly created resources](https://docs.meshery.io/concepts/architecture/meshsync#greenfield-tracking-newly-created-resources)

**Comment by ayushrakesh** [comment]
@leecalcote Please assign this issue to me, I want to work.

**Comment by akshansh-modi** [comment]
@leecalcote i would like to work on this .

**Comment by akshansh-modi** [comment]
hey @leecalcote i made the change and all the test cases in meshkit are passing

**Comment by leecalcote** [comment]
@akshansh-modi that's good to hear. I suspect that we won't know until you open a PR.

**Comment by leecalcote** [comment]
One item to verify is that when this change is made, you can still deploy a design, and have it's "Open in Vizualizer" link work.

**Comment by akshansh-modi** [comment]
ok @leecalcote

**Comment by MUzairS15** [comment]
Completed
