### ISSUE TITLE
Move InvokeGenerator to a centralized function of Meshkit.

### ISSUE THREAD

**Issue by Jougan-0** [meshery/meshkit#541]
**Current Behavior**

When we run `mesheryctl registry generate` we [InvokeGenerator](https://github.com/meshery/meshery/blob/c9728aaaacb4566bf8bc1b2952003083363ae170/mesheryctl/internal/cli/root/registry/generate.go#L144) directly inside the mesheryctl command rather it should be a centralized function in meshkit that can be reused in server as well.

**Desired Behavior**

Update meshkit to contain this functionality.
---
**Resources**

**Alternatives / Additional Context**

**Comment by MUzairS15** [comment]
@Jougan-0 We should reassign this issue.

**Comment by Jougan-0** [comment]
I'll complete this PR after adding some recent changes
