### ISSUE TITLE
Debug logging configurable

### ISSUE THREAD

**Issue by kumarabd** [meshery/meshkit#56]
**Description**
Currently the method to switch between `Debug` logs is not functional.

**Expected Behavior**
Debug logs should be configurable based on parameter input.

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

**Comment by leecalcote** [comment]
@Aisuko, part of what we're looking to do here is to refrain from a lot of extra debug logs being emitted from Meshery Operator. I wonder if you might want to take on the issue... ?

**Comment by Aisuko** [comment]
> @Aisuko, part of what we're looking to do here is to refrain from a lot of extra debug logs being emitted from Meshery Operator. I wonder if you might want to take on the issue... ?

Too much busy these days, but I will try to take a look,  but may not do a quick report
